version: "3"
services:
  python:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "8889:8888"
    command: jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
